name = "evenementen-refresh"
main = "cloudflare-worker.js"
compatibility_date = "2025-01-01"
keep_vars = true

[vars]
GITHUB_OWNER = "mrsjonnie"
GITHUB_REPO = "evenementen"
GITHUB_WORKFLOW_FILE = "update-events.yml"
